apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: github-tests-go-rehiluvn
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap-test-organization-jk/github-tests-go-rehiluvn:70ea9848564f89383936f5fe52a36d53506472d1
        name: container-image  
