apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: github-tests-go-rehiluvn
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/github-tests-go-rehiluvn:c55818f44ddb3505e2fa8f36a0f48bd3b9148c2a
          name: container-image
